### ISSUE TITLE
Please add README.md!

### ISSUE THREAD

**Issue by fexcode** [BaiChuanByte/crain#1]
Please add README.md!

**Comment by BaiChuanByte** [comment]
Have fixed. Thanks!

**Comment by fexcode** [comment]
wtf bro，u r even still remembering this prj?! unbelievable!



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 14, 2025 19:53 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [BaiChuanByte/crain] Please add README.md! (Issue #1)


BaiChuanByte left a comment (BaiChuanByte/crain#1)
 
Have fixed.

**Comment by BaiChuanByte** [comment]
> wtf bro，u r even still remembering this prj?! unbelievable!
> […](#)

of course ()
